variable "spec" {
  description = "Resource Profile manifest spec (the .spec block from the env manifest)."
  type        = any
}

variable "ssh_pubkey_path" {
  description = "Path to the per-env SSH public key (operator-local), supplied by bin/tf-apply.sh from the resolver. No default — there are no hardcoded paths."
  type        = string
}

variable "awx_control_node_ssh_pubkey_path" {
  description = <<-EOT
    Path to the per-env AWX→control-node SSH public key (ADR-0016 Path A),
    rendered into cloud-init `ssh_authorized_keys` so the AWX EE pod can SSH into
    the control node. The matching private key lives in the env's sops bundle
    (generated by init-wizard.sh) and is materialized at run time by
    run-playbook.sh. Supplied by bin/tf-apply.sh from the resolver — no default.
  EOT
  type        = string
}

variable "ssh_key_name" {
  description = "Fallback name of the hcloud_ssh_key resource. Wizard-created envs should set spec.provider.cloud.ssh_key_name."
  type        = string
  default     = "k3s-hetzner"
}

variable "private_network_ip_range" {
  description = "Outer IP range for the private network. Manifest only declares the subnet (/28); the network itself was created with a /24 by provision-nodes.sh."
  type        = string
  default     = "10.0.0.0/24"
}

variable "firewall_name" {
  description = "Fallback name of the hcloud_firewall. Wizard-created envs should set spec.provider.cloud.firewall_name."
  type        = string
  default     = "k3s-nodes"
}

variable "server_label_cluster" {
  description = "Fallback value of the 'cluster' label on each server. Wizard-created envs should set spec.provider.cloud.server_label_cluster."
  type        = string
  default     = "dmf-infra"
}

variable "lb_name" {
  description = "Name of the existing CCM-managed load balancer (looked up via data source for Cloudflare A records)."
  type        = string
  default     = "dmf-traefik"
}

variable "publish_lb_dns_records" {
  description = "When true, look up the CCM-managed load balancer and publish Cloudflare A records. Keep false for first Layer-1 apply because the CCM creates the LB later."
  type        = bool
  default     = false
}
