#!/usr/bin/env bash
# wizard-noninteractive-parity.sh — prove interactive and answers-file renders
# are structurally equivalent for the sandbox lane.
#
# Hermetic:
#   - temp DMF_DATA_ROOT
#   - temp SOPS_AGE_KEY_FILE
#   - throwaway SSH key for the sandbox node-login path
#   - skips cleanly if required tools are missing
#
# Compares:
#   - same file set
#   - same bundle key paths after decryption
#   - normalized manifest/main.yml content
#
# Secret bytes are intentionally allowed to differ.

set -euo pipefail

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "SKIP: $1 not on PATH"; exit 0; }
}

echo "=== wizard-noninteractive-parity test ==="

for cmd in sops age age-keygen yq python3 ssh-keygen bash; do
  need_cmd "$cmd"
done

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WIZARD="${REPO_DIR}/bin/init-wizard.sh"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

export DMF_DATA_ROOT="${WORK_DIR}/dmf-data"
export SOPS_AGE_KEY_FILE="${WORK_DIR}/age/keys.txt"
mkdir -p "${DMF_DATA_ROOT}" "${WORK_DIR}/age" "${WORK_DIR}/bin"

AGE_PUBKEY_FILE="${WORK_DIR}/age.pub"
age-keygen -o "${SOPS_AGE_KEY_FILE}" >/dev/null 2>&1
age-keygen -y "${SOPS_AGE_KEY_FILE}" > "${AGE_PUBKEY_FILE}"

NODE_KEY="${WORK_DIR}/sandbox-node-key"
ssh-keygen -t ed25519 -N "" -f "${NODE_KEY}" -C "wizard-parity-sandbox" >/dev/null 2>&1

interactive_log="${WORK_DIR}/interactive.log"
noninteractive_log="${WORK_DIR}/noninteractive.log"

interactive_answers=$'2\nmarty-mcfly\nmarty@dmf.test\nMarty McFly\nsandbox-demo\n203.0.113.10\nlima\n'"${NODE_KEY}"$'\nlima0\ny\n'
if ! printf '%s' "${interactive_answers}" | bash "${WIZARD}" >"${interactive_log}" 2>&1; then
  cat "${interactive_log}" >&2
  fail "interactive wizard run failed"
fi

interactive_env_id="$(grep -m1 '^  env_id:' "${interactive_log}" | awk '{print $2}')"
[ -n "${interactive_env_id}" ] || fail "could not parse interactive env_id"
interactive_env_root="${DMF_DATA_ROOT}/envs/${interactive_env_id}"
[ -d "${interactive_env_root}" ] || fail "interactive env root missing: ${interactive_env_root}"

answers_file="${WORK_DIR}/answers.yaml"
cat > "${answers_file}" <<EOF
schema_version: 1
provider: sandbox
operator:
  username: marty-mcfly
  email: marty@dmf.test
  display: "Marty McFly"
sandbox:
  label: sandbox-demo
  node_ip: 203.0.113.10
  ansible_user: lima
  iface: lima0
  ssh_private_key_path: ${NODE_KEY}
EOF

if ! bash "${WIZARD}" --non-interactive "${answers_file}" >"${noninteractive_log}" 2>&1; then
  cat "${noninteractive_log}" >&2
  fail "non-interactive wizard run failed"
fi

noninteractive_env_id="$(grep -m1 '^  env_id:' "${noninteractive_log}" | awk '{print $2}')"
[ -n "${noninteractive_env_id}" ] || fail "could not parse non-interactive env_id"
noninteractive_env_root="${DMF_DATA_ROOT}/envs/${noninteractive_env_id}"
[ -d "${noninteractive_env_root}" ] || fail "non-interactive env root missing: ${noninteractive_env_root}"

list_files() {
  find "$1" -type f | sed "s|^$1/||" | sort
}

normalize_text() {
  python3 - "$1" "$2" "$3" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
env_a = sys.argv[2]
env_b = sys.argv[3]

text = path.read_text()
text = text.replace(env_a, "<ENV_ID>")
text = text.replace(env_b, "<ENV_ID>")
text = re.sub(r'^.*Generated by init-wizard\.sh on .*$', '', text, flags=re.M)
text = re.sub(r'^.*created: .*$', '', text, flags=re.M)
text = re.sub(r'^.*created_at: .*$', '', text, flags=re.M)
print(text)
PY
}

for rel in \
  .sops.yaml \
  bundle.sops.yaml \
  manifest.yaml \
  inventory/hosts.ini \
  inventory/group_vars/all/main.yml \
  ssh/awx-control-node.pub
do
  [ -f "${interactive_env_root}/${rel}" ] || fail "missing interactive file: ${rel}"
  [ -f "${noninteractive_env_root}/${rel}" ] || fail "missing non-interactive file: ${rel}"
done

if ! diff -u <(list_files "${interactive_env_root}") <(list_files "${noninteractive_env_root}"); then
  fail "file sets differ between interactive and non-interactive renders"
fi

interactive_bundle_keys="$(sops -d "${interactive_env_root}/bundle.sops.yaml" | yq -o=json '.' | jq -r 'paths(scalars) | map(tostring) | join(".")' | sort -u)"
noninteractive_bundle_keys="$(sops -d "${noninteractive_env_root}/bundle.sops.yaml" | yq -o=json '.' | jq -r 'paths(scalars) | map(tostring) | join(".")' | sort -u)"
if [ "${interactive_bundle_keys}" != "${noninteractive_bundle_keys}" ]; then
  printf '%s\n' "${interactive_bundle_keys}" > "${WORK_DIR}/interactive.bundle.keys"
  printf '%s\n' "${noninteractive_bundle_keys}" > "${WORK_DIR}/noninteractive.bundle.keys"
  diff -u "${WORK_DIR}/interactive.bundle.keys" "${WORK_DIR}/noninteractive.bundle.keys" >&2 || true
  fail "decrypted bundle key paths differ"
fi

for env_root in "${interactive_env_root}" "${noninteractive_env_root}"; do
  kind="$(sops -d "${env_root}/bundle.sops.yaml" | yq -r '.kind')"
  [ "${kind}" = "BootstrapSecretBundle" ] || fail "unexpected bundle kind in ${env_root}: ${kind}"
  schema_version="$(sops -d "${env_root}/bundle.sops.yaml" | yq -r '.metadata.schema_version')"
  [ "${schema_version}" = "2" ] || fail "unexpected schema_version in ${env_root}: ${schema_version}"
done

interactive_manifest_norm="${WORK_DIR}/interactive.manifest.norm"
noninteractive_manifest_norm="${WORK_DIR}/noninteractive.manifest.norm"
interactive_main_norm="${WORK_DIR}/interactive.main.norm"
noninteractive_main_norm="${WORK_DIR}/noninteractive.main.norm"

normalize_text "${interactive_env_root}/manifest.yaml" "${interactive_env_id}" "${noninteractive_env_id}" > "${interactive_manifest_norm}"
normalize_text "${noninteractive_env_root}/manifest.yaml" "${interactive_env_id}" "${noninteractive_env_id}" > "${noninteractive_manifest_norm}"
normalize_text "${interactive_env_root}/inventory/group_vars/all/main.yml" "${interactive_env_id}" "${noninteractive_env_id}" > "${interactive_main_norm}"
normalize_text "${noninteractive_env_root}/inventory/group_vars/all/main.yml" "${interactive_env_id}" "${noninteractive_env_id}" > "${noninteractive_main_norm}"

if ! diff -u "${interactive_manifest_norm}" "${noninteractive_manifest_norm}"; then
  fail "normalized manifest.yaml differs"
fi

if ! diff -u "${interactive_main_norm}" "${noninteractive_main_norm}"; then
  fail "normalized inventory/group_vars/all/main.yml differs"
fi

hetzner_answers_file="${WORK_DIR}/hetzner-answers.yaml"
cat > "${hetzner_answers_file}" <<EOF
schema_version: 1
provider: hetzner
architecture: arm64
label: lab cluster
posture: test
operator:
  username: marty-mcfly
  email: marty@dmf.test
  display: "Marty McFly"
base_domain: lab.example.com
dns:
  cloudflare_api_token: fake-cloudflare-token
  cloudflare_zone_name: example.com
ssh:
  mode: generate
network:
  ssh_allow_ipv4: 203.0.113.10/32
  ssh_allow_ipv6: ""
hetzner:
  context: lab-cluster
  cloud_token: fake-hcloud-token
object_storage:
  b2_key_id: fake-b2-key-id
  b2_app_key: fake-b2-app-key
  b2_region: us-west-001
networking:
  tailscale_authkey: ""
  headscale_host: ""
openbao:
  breakglass_dir: ${WORK_DIR}/openbao-breakglass
  usb_base: ${WORK_DIR}/usb
EOF

mkdir -p "${WORK_DIR}/openbao-breakglass" "${WORK_DIR}/usb"
hetzner_log="${WORK_DIR}/hetzner.log"
if ! bash "${WIZARD}" --non-interactive "${hetzner_answers_file}" >"${hetzner_log}" 2>&1; then
  cat "${hetzner_log}" >&2
  fail "non-interactive hetzner smoke failed"
fi

hetzner_env_id="$(grep -m1 '^  env_id:' "${hetzner_log}" | awk '{print $2}')"
[ -n "${hetzner_env_id}" ] || fail "could not parse hetzner env_id"
hetzner_env_root="${DMF_DATA_ROOT}/envs/${hetzner_env_id}"

for rel in \
  .sops.yaml \
  bundle.sops.yaml \
  manifest.yaml \
  object-storage.tfvars \
  hetzner.tfvars \
  inventory/group_vars/all/main.yml \
  inventory/group_vars/all/openbao_secrets.yml \
  ssh/operator.pub \
  ssh/awx-control-node.pub
do
  [ -f "${hetzner_env_root}/${rel}" ] || fail "missing hetzner file: ${rel}"
done

hetzner_kind="$(sops -d "${hetzner_env_root}/bundle.sops.yaml" | yq -r '.kind')"
[ "${hetzner_kind}" = "BootstrapSecretBundle" ] || fail "unexpected hetzner bundle kind: ${hetzner_kind}"
hetzner_cloud_token_path="$(sops -d "${hetzner_env_root}/bundle.sops.yaml" | yq -o=json '.' | jq -r 'paths(scalars) | map(tostring) | join(".")' | grep -Fx 'providers.hetzner.cloud_token' || true)"
[ -n "${hetzner_cloud_token_path}" ] || fail "hetzner bundle missing providers.hetzner.cloud_token"

echo "PASS"
